; [core]
; plugins = autostart

; [autostart]
; chromium = chromium --kiosk --noerrdialogs --disable-infobars --touch-events=enabled --ignore-gpu-blocklist --enable-gpu-rasterization http://localhost:3000
; cursor = unclutter -idle 3

[core]
plugins = autostart

[autostart]
keyboard = wvkbd-mobintl -H -L 300
chromium = /usr/lib/chromium/chromium --kiosk --noerrdialogs --disable-infobars --touch-events=enabled --ozone-platform=wayland --enable-wayland-ime --ignore-gpu-blocklist --enable-gpu-rasterization http://localhost:3000
cursor = unclutter -idle 3